stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: "mkdir -p /go/src/github.com/rancher\nln -s `pwd` /go/src/github.com/rancher/pipeline-example-go\ncd
        /go/src/github.com/rancher/pipeline-example-go\ngo build -o bin/hello-server
        \ngo test -cover"
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: go-server:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 20
notification: {}
